[package]
name = "casper-engine-test-support"
version = "0.3.1" # when updating, also update 'html_root_url' in lib.rs
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"
description = "Library to support testing of Wasm smart contracts for use on the Casper network."
readme = "README.md"
documentation = "https://docs.rs/casper-engine-test-support"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casper-node/tree/master/grpc/test_support"
license-file = "../../LICENSE"

[dependencies]
casper-contract = { version = "0.3.1", path = "../../smart_contracts/contract", features = ["std"] }
casper-engine-grpc-server = { version = "0.3.1", path = "../server" }
casper-execution-engine = { version = "0.3.1", path = "../../execution_engine" }
casper-types = { version = "0.3.1", path = "../../types", features = ["std"] }
grpc = "0.6.1"
lmdb = "0.8.0"
log = "0.4.8"
num-rational = "0.3.0"
num-traits = "0.2.10"
once_cell = "1.5.2"
protobuf = "=2.8"
rand = "0.7.2"

[dev-dependencies]
version-sync = "0.9"

[features]
use-as-wasm = []
use-system-contracts = []
test-support = ["casper-engine-grpc-server/test-support", "casper-contract/test-support"]

