name: Dev-Net deploy

on:
  workflow_dispatch:
    inputs:
      branch_to_run:
        description: 'Branch to pull latest from'
        type: string
        default: 'dev' # Default to dev branch
        required: true

jobs:
  publish_protocol:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch_to_run }}

    - name: Display Branch
      run: echo "Running on branch ${{ github.event.inputs.branch_to_run }}"

    - name: Set CURRENT_HASH as environment variable
      run: echo "CURRENT_HASH=${{ github.sha }}" >> $GITHUB_ENV

    - name: Run script
      run: ./ci/dev_net_protocol_publish.sh

    # S3 upload